version: '3.5'

services:

  #mongo db  singel node
  mongodb:
    container_name: server_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: mongod --auth
    ports:
      - 37018:27017
    expose:
      - 37018
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - network

  #mongo db  singel node
  mongo-express:
    container_name: server_mongo_express
    image: mongo-express:latest
    environment:
      # auth for access mongodb server
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: server_mongodb

      # auth for access mongo express client

    ports:
      - 8081:8081
    expose:
      - 8081

    networks:
      - network
    depends_on:
      - mongodb


networks:
  network:
    driver: bridge

volumes:

  mongodb:
  mongoconfig:
