version: "3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: server_elastic_single_node
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
      #- ELASTIC_USERNAME=user
      #- ELASTIC_PASSWORD=password
      #- xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic


networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local