version: '3.5'

services:

  postgres:
    container_name: server_postgres
    image: postgres:13.4
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5436:5432
    networks:
      - network



networks:
  network:
    driver: bridge

volumes:
  postgres:
